events {}

http {
    split_clients "$remote_addr" $backend {
        90% "main";
        10% "exp";
    }

    upstream main [
        server main:5550;
    ]

    upstream exp {
        server exp:5550;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://$backend;
        }
    }
}